wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689960682.302183
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.5
      8:
      - 3
      - 5
